#include <config.h>
#include <errno.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include "vasnprintf.h"
#include "xalloc.h"
#include "xprintf.h"
#include "xvasprintf.h"
